name: Build

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Instala dependências
        working-directory: ./client
        run: npm install
      - name: Executa lint
        working-directory: ./client
        run: npm run lint
      - name: Executa build
        working-directory: ./client
        run: npm run build